name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Set permissions at the workflow level
permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # Use docker-container driver for better performance and multi-platform support
        driver: docker-container
        # Enable advanced buildkit features
        buildkitd-flags: |
          --allow-insecure-entitlement security.insecure
          --allow-insecure-entitlement network.host

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push with Bake
      uses: docker/bake-action@v4
      with:
        # Push only on main branch pushes (not PRs)
        push: ${{ github.event_name != 'pull_request' }}
        # Use our bake configuration file
        files: ./docker-bake.hcl
        # Pass dynamic values to bake
        set: |
          smartgliding-web.tags=${{ steps.meta.outputs.tags }}
          smartgliding-web.labels=${{ steps.meta.outputs.labels }}
        # Override registry from environment
        env: |
          REGISTRY=${{ env.REGISTRY }}/${{ github.repository_owner }}/smartgliding-web 